### ISSUE TITLE
Minimal Demo?

### ISSUE THREAD

**Issue by rubyFeedback** [JiFish/Storyteller#3]
Hey there,

I am working on my own code for fighting fantasy gamebooks, in ruby though.

I have a sinatra application that runs this too, but not online (it's already hosted
on rubygems.org, but mega-unfinished as of yet).

Do you think it would be possible for you to add a minimal demo? Ideally you
could host it online, BUT it is also ok to just have some small .php file or
something where we can quickly test the core functionality. I'd like to see
how Storyteller works and what it can offer, to learn from it.

Anyway that is my feature request - either way thank you for reading this.

**Comment by JiFish** [comment]
Hi!

Unfortunately, Storyteller is one of those projects that grew as requirements increased and is in desperate need of a refactor. In short: there is no good separation been the game logic and slack messaging. So there's no easy way to make it run without slack. Sorry.

If I ever properly return to this project, I will almost certainly have to completely rewrite it. Until then, what you see is what you get.

You might be able to learn something of my approach from the help docs: https://github.com/JiFish/Storyteller/blob/master/resources/help/help_ff.md (Fighting Fantasy) https://github.com/JiFish/Storyteller/tree/master/resources/help (The rest)
